[build]
  publish = "dist"
  command = "npm install""npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Force HTTPS redirect
[[redirects]]
  from = "http://advexcel.online/*"
  to = "https://advexcel.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.advexcel.online/*"
  to = "https://advexcel.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.advexcel.online/*"
  to = "https://advexcel.online/:splat"
  status = 301
  force = true

# API proxy for email verification
[[redirects]]
  from = "/api/send-otp"
  to = "/.netlify/functions/send-otp"
  status = 200

[[redirects]]
  from = "/api/verify-otp"
  to = "/.netlify/functions/verify-otp"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https: wss:; frame-src 'self';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
